name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Déploie à chaque push sur `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/tbot-451318/telegram-bot

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy telegram-bot \
            --image gcr.io/tbot-451318/telegram-bot \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
